{ ... }:
{
  wayland.windowManager.hyprland.settings = {
    env = [
      "__GLX_VENDOR_LIBRARY_NAME,nvidia"
      "__GL_HDR_METADATA,1"
      "_JAVA_AWT_WM_NONREPARENTING,1"
      "_JAVA_OPTIONS, -Dawt.useSystemAAFontSettings=on"
      "BEMENU_BACKEND,wayland"
      "CLUTTER_BACKEND,wayland"
      "CLUTTER_BACKEND,wayland"
      "DXVK_HDR,1"
      "ECORE_EVAS_ENGINE,wayland_egl"
      "EGL_PLATFORM,wayland"
      "ELECTRON_OZONE_PLATFORM_HINT,auto"
      "ELM_ACCEL,opengl"
      "ELM_DISPLAY,wl"
      "ELM_ENGINE,wayland_egl"
      "ELM_SCALE,1.5"
      "EL_DPI_FACTOR,1.5"
      "ENABLE_HDR_WSI,1"
      "GBM_BACKENDS_PATH,/usr/lib/gbm"
      "GBM_BACKEND,nvidia"
      "GDK_BACKEND,wayland,x11"
      # "GDK_DPI_SCALE,1.7"
      # "GDK_SCALE,1.8"
      "LIBSEAT_BACKEND,logind"
      "LIBVA_DRIVERS_PATH,/usr/lib/dri"
      "LIBVA_DRIVER_NAME,nvidia"
      "MOZ_DISABLE_RDD_SANDBOX,1"
      "MOZ_ENABLE_WAYLAND,1"
      "NO_AT_BRIDGE,1"
      "NVD_BACKEND,direct"
      "NVIDIA_WAYLAND_USE_SPECIALIZATION_CONSTANTS,1"
      # "QT_AUTO_SCREEN_SCALE_FACTOR,1"
      "QT_QPA_PLATFORMTHEME,qt6ct"
      "QT_QPA_PLATFORM,wayland;xcb"
      "QT_QUICK_CONTROLS_STYLE,org.hyprland.style"
      # "QT_SCALE_FACTOR,1.4"
      # "QT_WAYLAND_DISABLE_WINDOWDECORATION,1"
      "QT_WAYLAND_FORCE_DPI,physical"
      "SAL_USE_VCLPLUGIN,gtk4"
      "SDL_VIDEODRIVER,wayland"
      "TDESKTOP_DISABLE_GTK_INTEGRATION,1"
      "VDPAU_DRIVER,nvidia"
      "WINIT_UNIX_BACKEND,wayland"
      "WLR_DRM_DEVICES,/dev/dri/card1"
      "WLR_NO_HARDWARE_CURSORS,1"
      "WLR_RENDERER_ALLOW_SOFTWARE,1"
      "XDG_CURRENT_DESKTOP,Hyprland"
      "XDG_CURRENT_SESSION,Hyprland"
      "XDG_SESSION_DESKTOP,Hyprland"
      "XDG_SESSION_TYPE,wayland"
    ];
  };
}
