[pyprland]
plugins = ["scratchpads"]

# [scratchpads.terminals]
# animation = "fromTop"
# margin = 50
# size = "75% 60%"
# max_size = "1920px 100%"
#
# [scratchpads.term]
# command = "foot"
# class = "foot-float"
# use = "terminals"

# [pyprland]
# plugins = [ "scratchpads" ]
#
[scratchpads.term]
command = "kitty --class kitty-float"
class = "kitty-float"
size = "70% 70%"
margin = 50
animation = "fromTop"
unfocus = "hide"

[scratchpads.yazi]
command = "kitty --class explorer -e yazi"
class = "explorer"
size = "90% 90%"
margin = 50
animation = "fromBottom"
unfocus = "hide"

[scratchpads.filemanager]
animation = "fromBottom"
command = "thunar"
class = "thunar"
size = "80% 80%"
skip_windowrules = ["aspect", "workspace"]
