{ ... }: {
  wayland.windowManager.hyprland.settings = {
    layerrule = [
      "animation fade, caelestia-(drawers|background)"
      "animation fade, hyprpicker" # Colour picker out animation
      "animation fade, logout_dialog" # wlogout
      "animation fade, selection" # slurp
      "animation fade, wayfreeze"
      "animation popin 80%, launcher"
      "blur, caelestia-drawers"
      "blur,^(gtk-layer-shell)$"
      "blur, launcher"
      "ignorealpha 0.57, caelestia-drawers"
      "noanim, caelestia-(border-exclusion|area-picker)"
    ];

    windowrule = [
      "center 1, class:foot, title:nmtui"
      "center 1, class:nwg-look"
      "center 1, class:org.gnome.Settings"
      "center 1, class:org.pulseaudio.pavucontrol|yad-icon-browser"
      "float, class:blueman-manager"
      "float, class:com-atlauncher-App, title:ATLauncher Console"
      "float, class:com.github.GradienceTeam.Gradience"
      "float, class:feh"
      "float, class:file-roller"
      "float, class:foot, title:nmtui"
      "float, class:guifetch"
      "float, class:imv"
      "float, class:nwg-look"
      "float, class:org.gnome.FileRoller"
      "float, class:org.gnome.Settings"
      "float, class:org.pulseaudio.pavucontrol|yad-icon-browser"
      "float, class:org.quickshell"
      "float, class:system-config-printer"
      "float, class:wev"
      "float, class:yad"
      "float, class:zenity"
      "float, title:.* Properties"
      "float, title:(Select|Open)( a)? (File|Folder)(s)?"
      "float, title:Export Image as PNG"
      "float, title:File (Operation|Upload)( Progress)?"
      "float, title:Friends List, class:steam"
      "float, title:GIMP Crash Debug"
      "float, title:Library"
      "float, title:Picture(-| )in(-| )[Pp]icture"
      "float, title:Save As"
      "idleinhibit always, class:steam_app_[0-9]+"
      "immediate, class:steam_app_[0-9]+"
      "keepaspectratio, title:Picture(-| )in(-| )[Pp]icture"
      "move 100%-w-2% 100%-w-3%, title:Picture(-| )in(-| )[Pp]icture"
      "noblur, title:Fusion360|(Marking Menu), class:fusion360.exe"
      "nodim, xwayland:1, title:win[0-9]+"
      "noshadow, xwayland:1, title:win[0-9]+"
      "pin, title:Picture(-| )in(-| )[Pp]icture"
      "rounding 10, title:, class:steam"
      "rounding 10, xwayland:1, title:win[0-9]+"
      "size 50% 60%, class:nwg-look"
      "size 60% 70%, class:foot, title:nmtui"
      "size 60% 70%, class:org.pulseaudio.pavucontrol|yad-icon-browser"
      "size 70% 80%, class:org.gnome.Settings"
      "workspace special:communication, class:discord|equibop|vesktop|whatsapp"
      "workspace special:music, class:feishin|Spotify|Supersonic"
      "workspace special:music, initialTitle:Spotify( Free)?"
      "workspace special:sysmon, class:btop"
      "workspace special:todo, class:Todoist"
    ];

    windowrulev2 = [
      "animation slide down, class:^(explorer)$"
      "animation slide up, class:^(foot-float)$"
      "animation slide up, class:^(kitty-float)$"
      "dimaround, class:^(gcr-prompter)$"
      "dimaround, class:^(org.mate.polkit-mate-authentication-agent-1)$"
      "dimaround, class:^(xdg-desktop-portal-gtk)$"
      "dimaround, class:^(xdg-desktop-portal-hyprland)$"
      "float,class:^(com.github.Aylur.ags)$"
      "float,class:^(confirm)$"
      "float,class:^(confirmreset)$"
      "float,class:^(deluge)$"
      "float,class:^(dialog)$"
      "float,class:^(download)$"
      "float,class:^(error)$"
      "float,class:^(explorer)$"
      "float,class:^(file_progress)$"
      "float,class:^(foot-float)$"
      "float,class:^(kitty-float)$"
      "float,class:^(notification)$"
      "float,class:^(org.mate.polkit-mate-authentication-agent-1)$"
      "float,class:^(qt5ct)$"
      "float,class:^(qt6ct)$"
      "float,class:^(xdg-desktop-portal)$"
      "float,class:^(xdg-desktop-portal-gtk)$"
      "float,class:^(xdg-desktop-portal-hyprland)$"
      "float,title:^(branchdialog)$"
      "float,title:^(Confirm to replace files)"
      "float,title:^(File Operation Progress)"
      "float,title:^(Open File)$"
      "idleinhibit focus, class:^(brave)$, title:^(.*YouTube.*)$"
      "idleinhibit focus, class:^(mpv)$"
      "idleinhibit fullscreen, class:^(brave)$"
      "minsize 1 1, title:^()$,class:^(keepassxc)$"
      "minsize 1 1, title:^()$,class:^(steam)$"
      "noblur,class:^()$,title:^()$"
      "noanim,class:^(xwaylandvideobridge)$"
      "nofocus,class:^(xwaylandvideobridge)$"
      "noinitialfocus,class:^(xwaylandvideobridge)$"
      "opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$"
      "opacity 0.80 0.80,class:^(ags)$"
      "opacity 0.90 0.70,class:^(org.mate.polkit-mate-authentication-agent-1)$"
      "opacity 0.90 0.70,class:^(pavucontrol)$"
      "opacity 0.90 0.80,class:^(Spotify)$"
      "opacity 0.90 0.80,class:^(steamwebhelper)$"
      "opacity 0.90 0.80,class:^(WebCord)$"
      "opacity 0.90 0.80,class:^(discord)$"
      "opacity 0.90 0.80,class:^(qt5ct)$"
      "opacity 0.90 0.90,class:^(explorer)$"
      "opacity 0.90 0.90,class:^(foot-float)$"
      "opacity 0.90 0.90,class:^(footclient)$"
      "opacity 0.90 0.90,class:^(kitty)$"
      "opacity 0.90 0.90,class:^(Thunar)$"
      "opacity 0.95 0.95,class:^(Code)$"
      "opacity 0.95 0.95,class:^(foot)$"
      "size 40% 20%,class:^(org.mate.polkit-mate-authentication-agent-1)$"
      "size 40% 30%,title:^(Volume Control)$"
      "size 40% 40%,class:^(deluge-gtk)$"
      "size 40% 40%,class:^(Download)$"
      "size 40% 40%,title:^(Open File)$"
      "size 40% 40%,title:^(Save File)$"
      "size 70% 70%,class:^(foot-float)$"
      "stayfocused, title:^()$,class:^(keepassxc)$"
      "stayfocused, title:^()$,class:^(steam)$"
      "workspace special silent,class:^(explorer)$"
      "workspace special silent,class:^(foot-float)$"
    ];
  };
}
