{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    aide
    bleachbit
    btop
    cached-nix-shell
    cachix
    exfatprogs
    fastfetch
    ffmpeg
    gnumake
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-plugins-bad
    imagemagick
    jq
    killall
    linux-firmware
    mu
    nodejs_24
    openssl
    piper
    protonvpn-gui 
    python313 
    gcc15
    killall
    tree
    transmission_4-qt6
    typescript
    unzip
    wget
    wl-clipboard
    kdePackages.dolphin
  ];
}
