{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    aide
    bleachbit
    btop
    cached-nix-shell
    cachix
    exfatprogs
    fastfetch
    ffmpeg
    gnumake
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-plugins-bad
    imagemagick
    go
    jq
    file
    killall
    linux-firmware
    mu
    nodejs_24
    openssl
    piper
    poppler-utils
    resvg
    python313
    gcc15
    killall
    tree
    transmission_4-qt6
    typescript
    unzip
    wget
    wl-clipboard
    libvterm
    aubio
    brightnessctl
    ddcutil
    lm_sensors
    libqalculate
    app2unit
    fftw
    xkeyboard-config
    cmake
    ninja
    pkg-config
  ];
}
