{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    aide
    bleachbit
    btop
    cached-nix-shell
    cachix
    exfatprogs
    fastfetch
    ffmpeg
    gnumake
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gst-plugins-bad
    imagemagick
    jq
    killall
    linux-firmware
    mu
    neovim
    nodejs_24
    openssl
    piper
    python313
    tree
    typescript
    unzip
    wget
    wl-clipboard
  ];
}
