# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-50b81864-93a4-49e3-9d19-7f9d8474cf99";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-50b81864-93a4-49e3-9d19-7f9d8474cf99".device = "/dev/disk/by-uuid/50b81864-93a4-49e3-9d19-7f9d8474cf99";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7AC0-3065";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-374fa84a-a386-4666-bd07-6a87c6c853a8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
